name: test
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - systems/edge

permissions:
  contents: read
jobs:
  front:
    runs-on: Ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.17.1
      - run: cd deno && deno run -A dnt.ts
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-
      - run: pnpm run lint
      - run: pnpm run test
